### ISSUE TITLE
Missing gost.lib

### ISSUE THREAD

**Issue by tmarkettos** [rororor/a5v11-mod-01#1]
Hello,
I'd like to modify your hub PCB design for a different project - the single sided layout is almost what I need so I only need to remove some of your extra components and tweak the layout a bit.

However, the project needs /home/qwer1/work/projects/lib/kicad/gost.lib which I can't seem to find.  Is this available anywhere?  I see there's a kicad-symbols-gost repo, but I don't think it's the same thing.

Thanks
Theo

**Comment by rororor** [comment]
added gost libs in 'sch' folder

**Comment by tmarkettos** [comment]
Brilliant, that works, thanks.

For anyone else using this, this is the patch to make it work with the local lib:
https://gist.github.com/tmarkettos/4a1b4dcf12096654e490ede852670e85
